//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoolStaffDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FoolStaffDataModelContainer : DbContext
    {
        public FoolStaffDataModelContainer()
            : base("name=FoolStaffDataModelContainer")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<Tesoreria> Tesoreria { get; set; }
        public virtual DbSet<User_Tesoreria> User_Tesoreria { get; set; }
        public virtual DbSet<Task> Task { get; set; }
    }
}
