//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoolStaffDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.UserInfo = new HashSet<UserInfo>();
        }
    
        public int Id { get; set; }
        public System.DateTime DataCreazione { get; set; }
        public Nullable<System.DateTime> DataOperazione { get; set; }
        public Nullable<System.DateTime> DataChiusura { get; set; }
        public string Stato { get; set; }
        public string Titolo { get; set; }
        public string Descrizione { get; set; }
        public short Priorita { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserInfo> UserInfo { get; set; }
    }
}
