//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoolStaffDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tesoreria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tesoreria()
        {
            this.User_Tesoreria = new HashSet<User_Tesoreria>();
        }
    
        public int Id { get; set; }
        public System.DateTime DataOperazione { get; set; }
        public string Operazione { get; set; }
        public decimal Totale { get; set; }
        public string Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Tesoreria> User_Tesoreria { get; set; }
    }
}
