//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoolStaffDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Tesoreria
    {
        public decimal Versamento { get; set; }
        public int TesoreriaId { get; set; }
        public string UserInfoId { get; set; }
    
        public virtual Tesoreria Tesoreria { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
