//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoolStaffDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Tesoreria
    {
        public decimal Versamento { get; set; }
        public int UserId { get; set; }
        public int TesoreriaId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Tesoreria Tesoreria { get; set; }
    }
}
